"""Control representations that need no external artifact.

- `random`: a frozen i.i.d. N(0,1) vector per locus, generated by hashing (seed, locus key, dim index), so the same
  locus gets the same vector in every dataset and no table is stored. It carries locus *identity* only.
- `position_only`: chromosome one-hot + multi-scale sinusoidal code of the genomic coordinate (periods 16 bp ..
  ~270 Mb). Neighbouring loci get similar vectors; no functional information.

Both let the classifier memorise "locus -> class"; comparing them with `functional` separates representation content
from coordinate memorisation.
"""
from __future__ import annotations

import numpy as np

from cfdna_origin.data.loci import CHROM_CODE, key_chrom_code, key_position
from cfdna_origin.representations.base import LocusEmbeddingStore, RepresentationManifest

_M1, _M2, _M3 = np.uint64(0x9E3779B97F4A7C15), np.uint64(0xBF58476D1CE4E5B9), np.uint64(0x94D049BB133111EB)


def _splitmix64(x: np.ndarray) -> np.ndarray:
    with np.errstate(over="ignore"):
        z = x + _M1
        z = (z ^ (z >> np.uint64(30))) * _M2
        z = (z ^ (z >> np.uint64(27))) * _M3
        return z ^ (z >> np.uint64(31))


def _uniform(x: np.ndarray) -> np.ndarray:
    return ((_splitmix64(x) >> np.uint64(11)).astype(np.float64) + 0.5) / float(1 << 53)


def _valid_key(keys: np.ndarray) -> np.ndarray:
    code = key_chrom_code(keys)
    return (code >= 1) & (code <= max(CHROM_CODE.values())) & (key_position(keys) > 0)


class RandomLocusEmbeddingStore(LocusEmbeddingStore):
    def __init__(self, dim: int = 256, seed: int = 0, name: str = "random"):
        self.seed = int(seed)
        self.manifest = RepresentationManifest(
            name=name, kind="random", dim=int(dim), source=f"splitmix64-boxmuller(seed={seed})",
            cpg_universe="any GRCh38 chr1-22,X,Y locus key",
            normalization={"type": "none", "distribution": "N(0,1) iid per dim", "data_derived": False},
            provenance={"generator": "splitmix64 hash of (seed, locus_key, dim) + Box-Muller", "seed": self.seed},
        )

    def covers(self, keys: np.ndarray) -> np.ndarray:
        return _valid_key(np.asarray(keys, dtype=np.int64))

    def _lookup(self, keys: np.ndarray) -> np.ndarray:
        out = np.empty((len(keys), self.dim), np.float32)
        j = np.arange(self.dim, dtype=np.uint64)
        base = _splitmix64(np.asarray(keys, dtype=np.int64).astype(np.uint64) ^ _splitmix64(np.uint64(self.seed)))
        for s in range(0, len(keys), 65536):
            h = _splitmix64(base[s : s + 65536, None] + j[None] * np.uint64(2))
            u1, u2 = _uniform(h), _uniform(h ^ _M3)
            out[s : s + 65536] = np.sqrt(-2.0 * np.log(u1)) * np.cos(2.0 * np.pi * u2)
        return out


class PositionOnlyStore(LocusEmbeddingStore):
    N_CHROM = 24

    def __init__(self, dim: int = 256, min_period: float = 16.0, max_period: float = 2.7e8, name: str = "position_only"):
        if dim <= self.N_CHROM or (dim - self.N_CHROM) % 2:
            raise ValueError(f"position_only dim must be > {self.N_CHROM} and dim-{self.N_CHROM} even")
        n_freq = (dim - self.N_CHROM) // 2
        self.periods = np.geomspace(min_period, max_period, n_freq)
        self.manifest = RepresentationManifest(
            name=name, kind="position", dim=int(dim), source="analytic",
            cpg_universe="any GRCh38 chr1-22,X,Y locus key",
            preprocessing={"chrom_one_hot": self.N_CHROM, "n_frequencies": n_freq,
                           "min_period_bp": min_period, "max_period_bp": max_period},
            normalization={"type": "none", "data_derived": False},
        )

    def covers(self, keys: np.ndarray) -> np.ndarray:
        return _valid_key(np.asarray(keys, dtype=np.int64))

    def _lookup(self, keys: np.ndarray) -> np.ndarray:
        keys = np.asarray(keys, dtype=np.int64)
        out = np.zeros((len(keys), self.dim), np.float32)
        out[np.arange(len(keys)), key_chrom_code(keys) - 1] = 1.0
        ang = key_position(keys).astype(np.float64)[:, None] * (2.0 * np.pi / self.periods)[None]
        out[:, self.N_CHROM :] = np.concatenate([np.sin(ang), np.cos(ang)], 1)
        return out
